# Change these first
owner: visidea # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Visidea website
    url: https://visidea.ai
    icon: https://visidea.ai/wp-content/uploads/2022/02/cropped-favicon_Tavola-disegno-1-1-192x192.png
  - name: Visidea APIs
    url: https://api.visidea.ai/api/health
    icon: https://visidea.ai/wp-content/uploads/2022/02/cropped-favicon_Tavola-disegno-1-1-192x192.png
  - name: Visidea dashboard
    url: https://app.visidea.ai/
    icon: https://visidea.ai/wp-content/uploads/2022/02/cropped-favicon_Tavola-disegno-1-1-192x192.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.visidea.ai
  # baseUrl: /your-repo-name
  logoUrl: https://visidea.ai/wp-content/uploads/2022/02/cropped-favicon_Tavola-disegno-1-1-192x192.png
  name: Visidea
  introTitle: "**Visidea** is the Visual Search and Product Recommendations SAAS for e-commerce websites."
  introMessage: This is the status page of the services of **Visidea** in real-time.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://visidea.ai

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
